language: scala

scala:
   - 2.12.4

jdk:
   - oraclejdk8

matrix:
  include:
  # works on Precise and Trusty
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - sbt
    env:
    - MATRIX_EVAL="CC=gcc-5.4 && CXX=g++-5.4"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/45cb5820ca70c8a3445e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
